Repository jenkinsci/bitbucket-branch-source-plugin, pull requests merged in 2020-01, with the labels that each got.

#272 Moving docs from docs.cloudbees.com
  README.adoc
  docs/USER_GUIDE.adoc
  docs/images/screenshot-1.png
  docs/images/screenshot-2.png
  docs/images/screenshot-3.png
  docs/images/screenshot-4.png
  docs/images/screenshot-5.png
  docs/images/screenshot-6.png
  docs/images/screenshot-8.png
  docs/images/screenshot-9.png
Labels: chore

#265 feat: be more verbose in build status notification exception
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
Labels: feature

#274 Added condition for 403 HTTP Status
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Labels: feature

#277 add max pagelen of 100 to /refs/branches call
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-refs-branches_pagelen_100.json
Labels: bug

#278 fix Job DSL by adding a DataboundSetter it can understand
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
Labels: bug
