Repository jenkinsci/bitbucket-branch-source-plugin, pull requests merged in 2021-11, with the labels that each got.

#511 (chore) minor cleanups
  .editorconfig
  .gitignore
  .travis.yml
  Jenkinsfile
  checkstyle.xml
Labels: chore

#512 Auto releaser
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-management.yml
  .mvn/maven.config
  pom.xml
Labels: chore

#509 add missing license file based on pom.xml
  LICENSE.txt
  pom.xml
Labels: chore

#495 Add personal access token support
  docs/USER_GUIDE.adoc
  pom.xml
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketAccessTokenAuthenticator.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketAccessTokenAuthenticatorSource.java
  src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/help-credentialsId.html
  src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/help-credentialsId.html
  src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait/help.html
  src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint/help-credentialsId.html
Labels: needs-manual-testing, feature

#519 Bump plugin from 4.30 to 4.31
  pom.xml
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningTest.java
  src/test/java/integration/ScanningFailuresTest.java
Labels: dependencies

#518 Reduce usage of deprecated BitbucketRepositoryType.
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMNavigatorIntegrationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMNavigatorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/UriResolverTest.java
  src/test/java/integration/ScanningFailuresTest.java
Labels: chore, java

#520 Reduce usage of deprecated BitbucketRepositoryType.
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketTagSCMHead.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BranchSCMHead.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SCMHeadWithOwnerAndRepo.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerHeadEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketAuthenticatorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevisionTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchDiscoveryTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/ForkPullRequestDiscoveryTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/OriginPullRequestDiscoveryTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/PublicRepoPullRequestFilterTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMTraitCommitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookRegistrationTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpointDescriptorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpointTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpointTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpointTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEventTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPushEventTest.java
  src/test/java/integration/ScanningFailuresTest.java
Labels: chore, java

#513 master vs main
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTraitTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEventTest.java
  src/test/java/integration/ScanningFailuresTest.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest/exclude_branches.xml
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest/exclude_branches.xml
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest/getRepositoryPayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/createPayloadFork.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/createPayloadOrigin.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/fulfilledPayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/rejectedPayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newCommit.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newDestination.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newDestinationCommit.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest/createPayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest/multipleChangesPayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest/updatePayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-pullrequests_page_1_pagelen_50.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-refs-branches_pagelen_100.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEventTest/apiResponse.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEventTest/updatePayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPushEventTest/updatePayload.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-branches_start_0_limit_200.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-pull-requests-1.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-pull-requests-2.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-pull-requests_start_0_limit_200.json
Labels: chore

#517 bump jenkins-bom 2.289.x
  pom.xml
  src/test/java/integration/ScanningFailuresTest.java
Labels: enhancement

#525 Use annotations consistently.
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudPage.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
  src/test/java/integration/ScanningFailuresTest.java
Labels: chore
