Repository jenkinsci/bitbucket-branch-source-plugin, pull requests merged in 2022-01, with the labels that each got.

#479 JENKINS-65909 request specific branches/tags
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HasRefsChangedRequest.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-branches_start_0_limit_200_filterText_feature-BB-1.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-branches_start_0_limit_200_filterText_feature-BB-2.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-branches_start_0_limit_200_filterText_main.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-branches_start_0_limit_200_filterText_release-release-1.json
Labels: enhancement, java

#535 add lgtm badge
  README.adoc
  README.md
Labels: chore, documentation

#547 Fix typos: not-build vs not-built
  .gitattributes
  Jenkinsfile
  LICENSE.txt
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceContext.java
  src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/config.jelly
Labels: chore
