Repository jenkinsci/bitbucket-branch-source-plugin, pull requests merged in 2023-09, with the labels that each got.

#760 Allow developer control of parallel testing
  Jenkinsfile
  pom.xml
Labels: chore

#764 Delete lgtm badge from README
  README.md
Labels: chore

#765 Make Git use LF newlines in *.java, *.properties
  .gitattributes
Labels: chore

#763 Decode webhook request body as UTF-8
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
Labels: bug, java

#549 534 | Multiple triggers of the same PR
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Labels: enhancement, java
