Repository jenkinsci/bitbucket-branch-source-plugin, pull requests merged in 2025-01, with the labels that each got.

#927 [JENKINS-64418] Add exponential backoff to BitBucket rate limit retry loop
  pom.xml
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketDefaultBranch.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketProject.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/ExponentialBackOffServiceUnavailableRetryStrategy.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/ExponentialBackOffServiceUnavailableRetryStrategyTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-browse-Jenkinsfile_at_feature_2Fpipeline.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-browse-folder-Jenkinsfile_at_feature_2Fpipeline.json
Labels: needs-manual-testing, feature

#954 [JENKINS-75083] Build statuses do not appear in list of pull requests in Bitbucket Server
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotifications.java
Labels: bug

#953 [JENKINS-75073] Missing serverUrl in fillCredentialsIdItems cause some credentials missing in the initial configuration
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceBuilder.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiFactory.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookAutoRegisterListener.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketApiUtils.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketCredentials.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
Labels: bug, needs-manual-testing

#966 Extract event anonymous inner classes from webhook processor.
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/AbstractNativeServerSCMHeadEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/AbstractSCMHeadEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPingHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PREvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerHeadEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerPushEvent.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/URLUtils.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiverTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessorTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/URLUtilsTest.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/cloud/pullrequest_created.json
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/cloud/pullrequest_rejected.json
Labels: chore

#971 Migrate from EE 8 to EE 9
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketLink.java
Labels: internal

#981 [JENKINS-75208] Checkout on bitbucket server fail with IllegalArgumentException "Name cannot contain '/'"
  src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
  src/test/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileTest.java
  src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-browse-Jenkinsfile_at_2c130d767a38ac4ef511797f221315f35a2aea55_type_true_blame_false.json
Labels: bug
